// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IRiCodeLine: typeof import('~icons/ri/code-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VpDemo: typeof import('.vitepress/theme/components/vp-demo.vue')['default']
    VpExample: typeof import('.vitepress/theme/components/demo/vp-example.vue')['default']
    VpSourceCode: typeof import('.vitepress/theme/components/demo/vp-source-code.vue')['default']
    WhaleTeam: typeof import('.vitepress/theme/components/WhaleTeam.vue')['default']
  }
}

export {}
